In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 불필요한 경고 안뜨게
import warnings
warnings.filterwarnings('ignore')

# 데이터 전처리 알고리즘(비지도학습)
# 문자열 데이터를 숫자로 변환한다.
from sklearn.preprocessing import LabelEncoder
# 표준편차 기반으로 표준화(컬럼 당 숫자 편차가 다르니까.)
# 잘못된 학습을 정상화 시키는 목적으로 사용함
from sklearn.preprocessing import StandardScaler # 젤 유명 표준화

# train data랑 test data 나눔
from sklearn.model_selection import train_test_split

#교차검증
from sklearn.model_selection import cross_val_score

# 평가 함수
# 정확도 평가 함수
from sklearn.metrics import accuracy_score

# mse 평가 함수
from sklearn.metrics import mean_squared_error

# 학습 알고리즘 - 분류
# 최 근접 이웃
# 학습시 : 주어진 데이터를 저장만 한다
# 예측시 : 주변의 데이터를 보고 가장 많은 결과로 결정한다
from sklearn.neighbors import KNeighborsClassifier

# 선형
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# 트리
# 학습시 : 주어진 데이터를 갖고 질문을 생성한다
# 예측시 : 질문을 통해 최종 결과 예측
from sklearn.tree import DecisionTreeClassifier

# 앙상블 - 다수의 알고리즘이 던지는 결과를 취합하여 최종 결과를 결정함
# 트리들을 사용한다
# 학습시 : 데이터를 랜덤하게 섞어서 80%를 추출한다.
# 추출된 데이터를 트리의 개수만큼 생성해 각 트리들에게 주고 학습 수행
# 예측시 : 각 트리가 던지는 결과를 취합하여 다수결의 원칙으로 최종결과 결정
from sklearn.ensemble import RandomForestClassifier

# 부스팅 - 앙상블 알고리즘이 잘못 예측한 데이터를 다시 학습하는 방식
# 학습과 예측 원리는 앙상블과 동일함
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

# 학습 알고리즘 - 회귀
# 최근접이웃
from sklearn.neighbors import KNeighborsRegressor

# 선형
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR

# 트리
from sklearn.tree import DecisionTreeRegressor
# 앙상블
from sklearn.ensemble import RandomForestRegressor
# 부스팅
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor

In [5]:
# 데이터
X = [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]

and_y = [0, 0, 0, 1] # 둘다 1이어야 1임
nand_y = [1, 1, 1, 0] # and_y를 뒤집은거
or_y = [0, 1, 1, 1] # 둘중 하나가 1이어야 1임
xor_y = [0, 1, 1, 0] # 같으면 1 다르면 0

In [3]:
model1 = KNeighborsClassifier()
model2 = LogisticRegression()
model3 = SVC()
model4 = DecisionTreeClassifier()
model5 = RandomForestClassifier()
model6 = AdaBoostClassifier()
model7 = GradientBoostingClassifier()

In [6]:
model1.fit(X, and_y)
model2.fit(X, and_y)
model3.fit(X, and_y)
model4.fit(X, and_y)
model5.fit(X, and_y)
model6.fit(X, and_y)
model7.fit(X, and_y)

GradientBoostingClassifier()

In [15]:
#pred1 = model1.predict(X) #데이터 수가 너무 적어서 에러남 파라미터 조정하면 되긴함
pred2 = model2.predict(X)
pred3 = model3.predict(X)
pred4 = model4.predict(X)
pred5 = model5.predict(X)
pred6 = model6.predict(X)
pred7 = model7.predict(X)

In [17]:
print(pred2) # 선형모델은 안됨
print(pred3)
print(pred4)
print(pred5)
print(pred6)
print(pred7)

[0 0 0 0]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]
[0 0 0 1]


In [19]:
# 사용할 학습 모델들을 생성한다.
model1 = KNeighborsClassifier()
model2 = LogisticRegression()
model3 = SVC()
model4 = DecisionTreeClassifier()
model5 = RandomForestClassifier()
model6 = AdaBoostClassifier()
model7 = GradientBoostingClassifier()

In [20]:
model1.fit(X, or_y)
model2.fit(X, or_y)
model3.fit(X, or_y)
model4.fit(X, or_y)
model5.fit(X, or_y)
model6.fit(X, or_y)
model7.fit(X, or_y)

GradientBoostingClassifier()

In [21]:
# pred1 = model1.predict(X) #데이터 수가 너무 적어서 에러남 파라미터 조정하면 되긴함
# k-NN은 선형 모델이 아니기 때매 파라미터 조정하면 될수도/안될수도
pred2 = model2.predict(X)
pred3 = model3.predict(X)
pred4 = model4.predict(X)
pred5 = model5.predict(X)
pred6 = model6.predict(X)
pred7 = model7.predict(X)

In [22]:
print(pred2) # 선형모델은 안됨
print(pred3)
print(pred4)
print(pred5)
print(pred6)
print(pred7)

[1 1 1 1]
[0 1 1 1]
[0 1 1 1]
[0 1 1 1]
[0 1 1 1]
[0 1 1 1]


In [23]:
# 사용할 학습 모델들을 생성한다.
model1 = KNeighborsClassifier()
model2 = LogisticRegression()
model3 = SVC()
model4 = DecisionTreeClassifier()
model5 = RandomForestClassifier()
model6 = AdaBoostClassifier()
model7 = GradientBoostingClassifier()

In [24]:
model1.fit(X, xor_y)
model2.fit(X, xor_y)
model3.fit(X, xor_y)
model4.fit(X, xor_y)
model5.fit(X, xor_y)
model6.fit(X, xor_y)
model7.fit(X, xor_y)

GradientBoostingClassifier()

In [25]:
# pred1 = model1.predict(X)
pred2 = model2.predict(X)
pred3 = model3.predict(X)
pred4 = model4.predict(X)
pred5 = model5.predict(X)
pred6 = model6.predict(X)
pred7 = model7.predict(X)

In [26]:
print(pred2) # 선형회귀는 안됨
print(pred3) # SVM이 선 두개 긋는거라 또 됨
print(pred4)
print(pred5)
print(pred6) # Adaboost 안됨 이것도 되기도 안되기도
print(pred7)

[0 0 0 0]
[0 1 1 0]
[0 1 1 0]
[0 1 1 0]
[0 0 0 0]
[0 1 1 0]
